### ISSUE TITLE
Allow to enable feature flag based on query string

### ISSUE THREAD

**Issue by filipgolonka** [opensoft/rollout#12]
Feature flag should be allowed to be enabled by query string part. Example:

Feature: Github integration
Settings:
- query string - yes - FF_facebookIntegration=true
- percentage - 0
- user - no
- group - no

It means, that query string will have the biggest priority.

`$rollout->isActive('feature_name', 'FF_facebookIntegration')` on page `http://localhost/page/10?FF_facebookIntegration=true` should return `true`.

What do you think? I can prepare PR for this functionality and extend also Symfony2 bundle.

**Comment by wsromek** [comment]
👍

**Comment by richardfullmer** [comment]
Fixed by #13
