### ISSUE TITLE
PDOStorageAdapter incorrect prepared statement?

### ISSUE THREAD

**Issue by dtisgodsson** [opensoft/rollout#7]
Hi there,

I'm attempting to integrate RollOut into a project of mine, however, I'm having issues with the PDOStorageAdapter and I think I know what's happening but just wanted to confirm.

On line 14:

        const STMT_UPDATE = 'UPDATE :table SET settings = :value WHERE key = :key';

Should `WHERE key = :key` be `WHERE name = :key` to be consistent with the other prepared statements?

If so, I can submit a pull request as this resolved my issue.

Cheers,
Darren

**Comment by mattclements** [comment]
I had the same error so have raised a Pull Request.

**Comment by richardfullmer** [comment]
Fixed.  Thanks @mattclements
